### ISSUE TITLE
YAML anchors are not preserved

### ISSUE THREAD

**Issue by svmn** [kislyuk/yq#126]
When using yq to edit yaml files, it deletes anchors and setting it values instead. Example

```yaml
anchor: &anchor "value"
key: *anchor
```

Running `yq -Y '.' test.yaml` will produce such output
```yaml
anchor: "value"
key: "value"
```

Expected to see original input with anchors.

**Comment by kislyuk** [comment]
There are no plans to support anchor round-tripping in yq. Because anchor representations are YAML-specific metadata, they are not easily accommodated in JSON without disrupting the document structure. Anchors and aliases are also difficult to deal with safely in untrusted input, so their use is not recommended.
