### ISSUE TITLE
Name collision with https://github.com/mikefarah/yq

### ISSUE THREAD

**Issue by whyman** [kislyuk/yq#141]
Wasnt this project once called `xq`?

**Comment by kislyuk** [comment]
Thanks. Yes, I established that redirect for the avoidance of confusion since this project also ships a utility called xq.

The other project does indeed have more stars, but has a substantially different philosophy. The author did not bother to search for anyone else using the name, and was not amenable to changing it early on when notified about the collision.

I appreciate the explanation and the intent of trying to help.

**Comment by simoniz0r** [comment]
> No, this project was always called yq, and it was started before the other one. All you need to do is look at the git history.
> 
> I find these types of questions incredibly rude, but I'm going to assume that you asked it in good faith and just didn't word it well.

I don't mean to be rude, but I did check the git history, and I'm quite confused...

![image](https://github.com/kislyuk/yq/assets/16279904/5d6a75ba-8bc7-47cb-b7c0-a0f773e7ddcf)

![image](https://github.com/kislyuk/yq/assets/16279904/8ddbaa44-2e8b-46e4-8088-f33ad1303f34)

**Comment by danielhoherd** [comment]
FWIW the other project has a reciprocal ticket https://github.com/mikefarah/yq/issues/189 and the conclusion was "there's nothing to be done", which IMHO is also rude, and user hostile.
