### ISSUE TITLE
--slurp doesn't work since 2.3.5

### ISSUE THREAD

**Issue by drigz** [kislyuk/yq#38]
If I try to use `--slurp` with yq, it gets incorrectly translated into `--slurpfile`. I am using Python 3.5.3.

```
> touch 2.yaml 3.yaml
> sudo pip3 install yq==2.3.4
> echo | yq -e --slurp '.[0] == .[1]' - 2.yaml 3.yaml
true
> sudo pip3 install yq==2.6.0
> echo | yq -e --slurp '.[0] == .[1]' - 2.yaml 3.yaml
jq: Bad JSON in --slurpfile .[0] == .[1] -: Could not open -: No such file or directory
```

This is linked to ArgumentParser's prefix matches as described in this [SO question](https://stackoverflow.com/questions/33900846/disable-unique-prefix-matches-for-argparse-and-optparse).

Workaround: use `-s` instead of `--slurp`.

**Comment by kislyuk** [comment]
Thank you for the thorough bug report and for identifying the root cause.

I have disabled argparse abbreviations on Python 3. I'm not sure if there is a good way to support this fix on Python 2, where the option does not exist. Python 2 should be deprecated in 17 months anyway :)

I will roll a patch release shortly.
