### ISSUE TITLE
xq woes

### ISSUE THREAD

**Issue by pkoppstein** [kislyuk/yq#65]
Installed via homebrew. Tried running `xq` only to be told that 

bash: /usr/local/bin/xq: /usr/local/opt/python/bin/python3.6: bad interpreter: No such file or directory

My system has python3.6, so I changed the first line of the xq file accordingly.

Now I'm told:

```
  File "/usr/local/bin/xq", line 4, in <module>
    from yq import main
ModuleNotFoundError: No module named 'yq'
```

Of course I'd appreciate any advice regarding how to achieve a successful installation, but I'm also curious as to why it seems to be so difficult to achieve a hassle-free distribution. Is it a python thing, or is it something to do with the joint behavior of python and homebrew?

Thanks.

**Comment by kislyuk** [comment]
Installing yq using `brew install python-yq` works for me (xq included). Your issue appears to be related to your Homebrew configuration. Consider re-installing Homebrew from scratch.

You can't simply change the path to the Python installation in the `/usr/local/bin/xq` executable, because the new interpreter you pointed it to uses a different site-packages location, without the yq library in it.

**Comment by pkoppstein** [comment]
Fortunately, there was no need to reinstall Homebrew itself.

Unfortunately, running `brew upgrade python-yq` was a no-op.

Fortunately, running `brew uninstall python-yq` succeeded, and then `brew install python-yq` fixed things.

Maybe some interleaving of 

```
pip install yq
brew install python-yq
brew upgrade python-yq
pip install xq
```

resulted in a python mish-mash.
